### ISSUE TITLE
图片怎么改为本地储存

### ISSUE THREAD

**Issue by qq547176052** [mlogclub/bbs-go#160]
图片怎么改为本地储存

**Comment by dandyhuang** [comment]
本地生成图片，然后用nginx去访问就好了

**Comment by alibabaaaaaa** [comment]
> <img alt="image" width="1018" src="https://user-images.githubusercontent.com/12603054/197477606-2beefa4c-9eb2-45b4-a277-879e12574d9f.png">
> 
> 本地生成图片，然后用nginx去访问就好了

正解
