### ISSUE TITLE
admin能成功吗

### ISSUE THREAD

**Issue by weidongbcn** [mlogclub/bbs-go#165]
debian@debian-PS63-Modern-8M:~/bbs/bbs-go/admin$ yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
debian@debian-PS63-Modern-8M:~/bbs/bbs-go/admin$ yarn serve
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'serve'
debian@debian-PS63-Modern-8M:~/bbs/bbs-go/admin$ yarn serve
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'serve'
debian@debian-PS63-Modern-8M:~/bbs/bbs-go/admin$

**Comment by alibabaaaaaa** [comment]
能成功

**Comment by bbbbbbbbbbbbba** [comment]
admin模块已经升级到vue3，可以解决该问题了，并且提供了docker镜像。
