### ISSUE TITLE
master分支 包名错误. common.ErrorNotLogin  那里

### ISSUE THREAD

**Issue by qbmiller** [mlogclub/bbs-go#172]
我改了，但是ide 默认4空格， 与原博主8空格冲突就不提交pr了

https://github.com/mlogclub/bbs-go/compare/master...qbmiller:bbs-go:master
<img width="632" alt="image" src="https://user-images.githubusercontent.com/7335567/187580459-dc7e7fcb-0d0c-4ba9-9bf0-d59b97ae3b07.png">

**Comment by alibabaaaaaa** [comment]
已修复
