### ISSUE TITLE
搜索是不是不管用啊

### ISSUE THREAD

**Issue by lengqingfeng** [mlogclub/bbs-go#192]
用官方搜索搜索不出相关帖子

**Comment by qbmiller** [comment]
搭建时候，部署下就好了。直接docker 部署。 我的
`
docker run -d \
--name elasticsearch \
-e "ES_JAVA_OPTS=-Xms512m -Xmx512m" \
-e "discovery.type=single-node" \
-v /home/ubuntu/elastic/es-data:/usr/share/elasticsearch/data \
-v /home/ubuntu/elastic/es-logs:/usr/share/elasticsearch/logs \
--privileged \
-p 9200:9200 \
elasticsearch:7.17.7
`

**Comment by bbbbbbbbbbbbba** [comment]
可以用，新版本已经不用elasticsearch了，使用golang实现了搜索。
