### ISSUE TITLE
admin模块无法用npm构建

### ISSUE THREAD

**Issue by heroineyy** [mlogclub/bbs-go#210]
1. 第一次使用了cnpm安装，报错，说npm版本没有换，我因为安装site没有报错和成功运行，就为更新到相应版本，尝试其他解决方案
2. 接着用npm安装，报错，看日志如下：
![image](https://github.com/mlogclub/bbs-go/assets/82981823/70959883-5826-4c8f-9df0-50323edf865a)
3.问chatgpt,chatgpt给的解决方案，尝试未果
![image](https://github.com/mlogclub/bbs-go/assets/82981823/84fc6e77-c565-4bef-a5b9-e13834bdb00d)
4. 百度一下，根据报错提示，使用npx -p npm@6 npm i --legacy-peer-deps 依旧不行
5. 使用npm i --legacy-peer-deps 也不行
6. 使用npm i --force 也不行

**Comment by Microanswer** [comment]
试试：
```
npm install yarn -g
```

然后:
```
yarn install
```

然后：
```
npm run serve
```

**Comment by bbbbbbbbbbbbba** [comment]
bbs-go4.0发布了，后台全部重写了，可以试下4.0版本。
