### ISSUE TITLE
DOCKER方式启动，验证码URL有误

### ISSUE THREAD

**Issue by towangle** [mlogclub/bbs-go#218]
docker-compose 启动，
打开后，接口http://192.168.3.187:3000/api/captcha/request  获取验证码图片：

验证码图片地址为：http://127.0.0.1:3000/api/captcha/show?captchaId=XSTLtmUsBfa3KfgcoGCv\u0026r=6ab2e49068784f5fa8ca7e54d2b82851

此处为何会使用127.0.0.1？

**Comment by bbbbbbbbbbbbba** [comment]
bbs-go已经全新改版，docker镜像也重新整理了，请参考文档：https://bbs-go.com 进行安装。
