### ISSUE TITLE
账号在非管理员权限下 在帖子管理菜单中会获得部分管理员权限

### ISSUE THREAD

**Issue by AliceDreamland** [mlogclub/bbs-go#229]
![1](https://github.com/mlogclub/bbs-go/assets/95115237/c7ddd147-85b7-438a-847a-1948798ff492)
![2](https://github.com/mlogclub/bbs-go/assets/95115237/5c493044-b6a3-4119-a05e-fe345c3355eb)
![3](https://github.com/mlogclub/bbs-go/assets/95115237/1decd3b7-9d06-496e-8e40-73d6d884b7b1)

![4](https://github.com/mlogclub/bbs-go/assets/95115237/eba356c3-1590-4170-98d7-51450ef73262)

**Comment by bbbbbbbbbbbbba** [comment]
感谢反馈，我们修复下。

**Comment by bbbbbbbbbbbbba** [comment]
已修复
