### ISSUE TITLE
建议将docker安装部署yml内的site的配置修改以正常显示验证码

### ISSUE THREAD

**Issue by snakeysky** [mlogclub/bbs-go#230]
- 我在vm上做测试，使用局域网地址访问前端，无法显示验证码，访问后台，提示network error。
- F12后发现加载失败的内容均为源localhost，在非本机调试的情况下，docker部署的默认打包里的baseurl写的不是0.0.0.0:3000就会导致开箱不能即用 ，考虑到开箱通用性，建议修改这个参数以便docker部署可以直接开箱即用。
- 另我想自己编译一个测试一下，发现前台模块内的baseurl改了后编译自有镜像就可以正常显示验证码了，后台admin模块编译镜像缺少/code/bbs-go/admin/dist 部分，导致编译无法成功。

**Comment by jkjoy** [comment]
是的 docker是存在这个问题的.
我尝试在反代的时候替换 localhost字段 成域名 只是前台可以显示 二维码 后台却不显示

**Comment by bbbbbbbbbbbbba** [comment]
> 是的 docker是存在这个问题的. 我尝试在反代的时候替换 localhost字段 成域名 只是前台可以显示 二维码 后台却不显示

最新版本的docker镜像已经调整了，该问题已经解决。
