### ISSUE TITLE
前端[后台管理]页面中，用户信息roles无法传递到后台顺利通过iris转化为正确格式数组的bug

### ISSUE THREAD

**Issue by Iteravse** [mlogclub/bbs-go#46]
本地搭建后尝试了后台管理的功能，发现并不能直接通过编辑用户信息添加角色，调试后发现，前台传输的roles是数组如下图：
![image](https://user-images.githubusercontent.com/34048239/80102747-ce921680-85a5-11ea-8796-3a5c84f2f905.png)
而这个信息传到后台时，控制器源码如下图使用simple.FormValueStringArray中的FormValue，并不能获取出正确的数据
![image](https://user-images.githubusercontent.com/34048239/80102113-ed43dd80-85a4-11ea-9817-7c1d0db7e6f2.png)
![image](https://user-images.githubusercontent.com/34048239/80102531-73602400-85a5-11ea-9c51-920768680ff7.png)
我尝试用其他方法来fix 这个bug，但我发现前端数组传到后台在iris中找不到直接回归数组的方法，roles这个key在后台已经变成了带下标的键了，直接formvalue('roles')是获取不到任何值的，iris在国内的相关文档少之又少，国外google不到类似的情况，所以这种问题到底怎么解决？

**Comment by alibabaaaaaa** [comment]
感谢反馈，这个问题我来解决， 是有办法解决的。

**Comment by Iteravse** [comment]
> 感谢反馈，这个问题我来解决， 是有办法解决的。

这应该不是个大问题，能直接说下iris应该用哪一个方法来正确的转化前端传来的数组嘛？我试了好几个都不行，然后iris的文档看了下也找不到对应的方法

**Comment by alibabaaaaaa** [comment]
> > 感谢反馈，这个问题我来解决， 是有办法解决的。
> 
> 这应该不是个大问题，能直接说下iris应该用哪一个方法来正确的转化前端传来的数组嘛？我试了好几个都不行，然后iris的文档看了下也找不到对应的方法

该问题已经修复，详见：https://github.com/mlogclub/bbs-go/commit/e91e99135e91b80b6d6dd265a1a48b8fb80e02fc
