### ISSUE TITLE
跑起服务后，注册时有问题

### ISSUE THREAD

**Issue by flyq** [mlogclub/bbs-go#53]
![image](https://user-images.githubusercontent.com/16486808/80984898-0d0ab980-8e61-11ea-919a-418e234afb5c.png)

每次注册时，就会弹出报错，报错信息见上图。

而且代码里面搜索 no such host 找不到对应的。

代码里面和`.jpg`相关的就只有这段 [utils.go](https://github.com/mlogclub/bbs-go/blob/master/server/common/uploader/utils.go#L12-L15) :

```shell
// generateKey 生成图片Key
func generateImageKey(data []byte) string {
	md5 := simple.MD5Bytes(data)
	return filepath.Join("images", simple.TimeFormat(time.Now(), "2006/01/02/"), md5+".jpg")
}
```
可能是qq邮箱的报错，也有可能是其他，我明天设置一下网易邮箱试试

**Comment by flyq** [comment]
https://mlog.club/topic/994
已经解决

**Comment by weirenren** [comment]
请教下：本地开发 图片上传等怎么配置的了？
  # 本地文件上传
  Local:
    Host: https://st.mlog.club/ # 上传文件域名
    Path: /data/www/st.mlog.club # 上传目录

**Comment by flyq** [comment]
> 请教下：本地开发 图片上传等怎么配置的了？
> 目前问题是图片上传路径不对，显示不了
> 
> # 本地文件上传
> Local:
> Host: https://st.mlog.club/ # 上传文件域名
> Path: /data/www/st.mlog.club # 上传目录

最新版应该包含对应的本地图片保存功能。如果没有，起一个http服务就行，然后把接口配置一下
