### ISSUE TITLE
Error 1146: Table 'bbsgo_db.t_topic_node' doesn't exist

### ISSUE THREAD

**Issue by tomriddle1234** [mlogclub/bbs-go#72]
你好，我使用时一开始用MySQL 5.6创建的数据库charset默认成了latin1，发现错误以后我drop了所有table，改了数据库charset和collation，重新用文档里的数据库SQL做了初始化，删除了静态生成的xml。

正常登陆admin后台，但是当我想创建第一个话题节点时，提示上面错误。请问怎么办？

**Comment by tomriddle1234** [comment]
经过检查bbs-go的log发现一行`level=error msg="Error 1071: Specified key was too long; max key length is 767 bytes"`，这个后面就是建表出问题的error。
于是研究了一下，发现MySQL 5.6的index最多只支持767bytes，bbs-go看来用了长的index，于是MySQL 5.6升级5.7就解决了。

**Comment by alibabaaaaaa** [comment]
> 经过检查bbs-go的log发现一行`level=error msg="Error 1071: Specified key was too long; max key length is 767 bytes"`，这个后面就是建表出问题的error。
> 于是研究了一下，发现MySQL 5.6的index最多只支持767bytes，bbs-go看来用了长的index，于是MySQL 5.6升级5.7就解决了。

是的， 是有这个问题。
