### ISSUE TITLE
docker-compose启动bbs-go论坛 server报错。

### ISSUE THREAD

**Issue by Blackcat308** [mlogclub/bbs-go#78]
standard_init_linux.go:211: exec user process caused "no such file or directory"
![image](https://user-images.githubusercontent.com/21216908/92871731-d872c400-f437-11ea-97c1-62d952ae3cb4.png)

求解答什么原因引起的？

**Comment by tomriddle1234** [comment]
我没用docker部署 不了解

**Comment by Blackcat308** [comment]
....

**Comment by Blackcat308** [comment]
已解决
