### ISSUE TITLE
在拥有禁言权限的时候禁言自己会出现bug

### ISSUE THREAD

**Issue by LolitaSquad** [mlogclub/bbs-go#84]
拥有禁言权限应该不允许禁言自己

在禁言自己后前端点击解除禁言不会生效，当前状体文字会先显示禁言解除  但是刷新页面后依然是禁言状态，但是在后台禁言状态

是现实 正常状态  实际是用户依然是禁言状态 无法发帖和删帖

**Comment by alibabaaaaaa** [comment]
已解决
