### ISSUE TITLE
点赞列表在显示多人点赞的情况下在手机端浏览会超出帖子范围

### ISSUE THREAD

**Issue by LolitaSquad** [mlogclub/bbs-go#85]
![1](https://user-images.githubusercontent.com/72801242/96098764-14042080-0f05-11eb-9ccb-4c463622f65b.png)
![2](https://user-images.githubusercontent.com/72801242/96098772-16667a80-0f05-11eb-81e5-8fb9e6caf839.png)

图片2中点赞列表中的其他点赞用户头像超出了帖子的范围

**Comment by alibabaaaaaa** [comment]
已经优化展示效果。
