### ISSUE TITLE
error 未传递

### ISSUE THREAD

**Issue by helloh2o** [mlogclub/bbs-go#86]
func(key cache.Key) (value cache.Value, e error) {
				value = repositories.UserRepository.Get(simple.DB(), key2Int64(key))
				return
			},
repositories.UserRepository.Get 没有传递error， 会导致loader中的e永远是nil，然后cache中的逻辑  （err always nil）永远都不会执行c.stats.RecordLoadError(loadTime)   [goburrow/cache/local.go line: 295]
        if err != nil {
		c.stats.RecordLoadError(loadTime)
		return nil, err
	}
	c.stats.RecordLoadSuccess(loadTime)
	en := newEntry(k, v, sum(k))
	c.setEntryWriteTime(en, now)
	c.setEntryAccessTime(en, now)
	c.sendEvent(eventWrite, en)
	return v, nil

**Comment by gaoyoubo** [comment]
然后呢？ 会有什么问题呢？

**Comment by alibabaaaaaa** [comment]
这里会有什么问题吗？ 你贴出代码之后我特意看了下，没发现啥问题啊？ 这里没有err信息，没找到就是没找到呀。

**Comment by helloh2o** [comment]
loader函数里面如果查询出错了，返回的err也是nil. 在cache里面永远不会执行
if err != nil {
c.stats.RecordLoadError(loadTime)
return nil, err
}
而是创建新Entry对象，值是nil。

**Comment by alibabaaaaaa** [comment]
> loader函数里面如果查询出错了，返回的err也是nil. 在cache里面永远不会执行
> if err != nil {
> c.stats.RecordLoadError(loadTime)
> return nil, err
> }
> 而是创建新Entry对象，值是nil。

可以提个pr给我吗？还是没get到你的点。

**Comment by helloh2o** [comment]
嗯，你修改了. 一个月前我抓过你的网站， 性能有待优化。 但最近又加入了es，gorm升级了v2。期待更完美。我也持续关注，如果可以也会push request  @alibabaaaaaa
