### ISSUE TITLE
Nuxt run always Error

### ISSUE THREAD

**Issue by SamJheng** [mlogclub/bbs-go#95]
![image](https://user-images.githubusercontent.com/33681236/103201990-3d412400-492c-11eb-9c53-8b57f01b59e7.png)

cd site
npm install
npm run dev

any one idea?

**Comment by gaoyoubo** [comment]
execute command `npm run lintfix`

**Comment by alibabaaaaaa** [comment]
execute command `npm run lintfix`

**Comment by SamJheng** [comment]
ok thanks !
